### PR TITLE
hide connections dialog for acnet sample

### PR DESCRIPTION
**Pull request by mattearnshaw**
https://github.com/OpenSourceBrain/geppetto-osb/issues/13

### CODE REVIEW

**Comment by tarelli** [comment]
@pgleeson @mattearnshaw hey guys, as a reminder what's deployed in comodl (and what will endup in osb) has the move_scripts branch for the samples so any fix should be merged there.

**Comment by pgleeson** [comment]
Just saw that... Will pull in these changes here on move_scripts. Do they still need to point to https://raw.githubusercontent.com/openworm/org.geppetto.model/development/src/main/resources/geppettoModel.ecore in development and .../master/..  in master?

**Comment by tarelli** [comment]
Now they are going to get loaded regardless but if we add something to the development schema one day that something wouldn't be available to the samples unless they point to the development schema  or until we merge to master. So it's more flexible if we keep the split in general (we can showcase samples with features not yet released if they come from the dev branch)...if it's not too painful to maintain :)

**Comment by pgleeson** [comment]
Ok, no problem. Added to move_scripts here https://github.com/OpenSourceBrain/OSB_Samples/commit/3ce6596d6f8f21b340a1489a52885d5705f19fe8

**Pull request merged**
